services:
  mongo:
    image: mongo:7
    container_name: eventhub-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - eventhub-mongo-data:/data/db

volumes:
  eventhub-mongo-data:
